### ISSUE TITLE
支付宝沙箱环境有问题

### ISSUE THREAD

**Issue by leielyq** [kingofglory/EasyPay#1]
EnvUtils.setEnv(EnvUtils.EnvEnum.SANDBOX);  无法访问

**Comment by kingofglory** [comment]
好的，我迟点抽空看看。你如果着急的话，可以把源码下载上来，直接替换。

**Comment by leielyq** [comment]
嗯，把sdk升级一下就有了

**Comment by kingofglory** [comment]
> 嗯，把sdk升级一下就有了

你方便提个PR吗？我可以把你的更新合并进来。还有，这三种支付你们都用了吗？还有没有什么问题？
