### ISSUE TITLE
 java.lang.NullPointerException 空指针异常

### ISSUE THREAD

**Issue by oneLZH** [kingofglory/EasyPay#11]
bugly 采集到的异常信息，目前只有微信支付有这个问题

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.xxx/com.xgr.wechatpay.activity.WXPayActivity}: java.lang.NullPointerException: NullPointerException in DoInvoke because of null receiver
--
 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2969)
 ......
java.lang.NullPointerException:NullPointerException in DoInvoke because of null receiver
com.xgr.wechatpay.activity.WXPayActivity.void onCreate(android.os.Bundle)(Native Method)
android.app.Activity.performCreate(Activity.java:7139)
android.app.Activity.performCreate(Activity.java:7130)
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2922)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3047)
android.app.ActivityThread.-wrap11(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loop(Looper.java:192)
android.app.ActivityThread.main(ActivityThread.java:6778)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
18 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

**Comment by kingofglory** [comment]
这个看起来是在系统框架里面崩了。报的数量多么？是否跟某些机型系统相关？能稳定复现吗？

**Comment by kingofglory** [comment]
797559567, 进这个QQ群来聊聊吧

**Comment by oneLZH** [comment]
目前是仅有这个机型
前后台状态：前台
设备机型：VIVO V1813A
系统版本：Android 8.1.0,level 27
ROM：vivo/FUNTOUCH
CPU架构：arm64-v8a

**Comment by pengjunhong** [comment]
@oneLZH 该问题是否解决 我前面也遇到，提了issue，但是后面说新版已经没有使用WXPayActivit，所以暂时也没处理。

**Comment by oneLZH** [comment]
> @oneLZH 该问题是否解决 我前面也遇到，提了issue，但是后面说新版已经没有使用WXPayActivit，所以暂时也没处理。

还没有解决，微信支付这块自己扩展用了

**Comment by kingofglory** [comment]
> @oneLZH 该问题是否解决 我前面也遇到，提了issue，但是后面说新版已经没有使用WXPayActivit，所以暂时也没处理。

你有稳定复现步骤么？麻烦提供下

**Comment by kingofglory** [comment]
你们调用都是用kotlin么？

**Comment by oneLZH** [comment]
> 你们调用都是用kotlin么？

没有用 kotlin

**Comment by pengjunhong** [comment]
@kingofglory 我这边也是在友盟崩溃日志看到的 手头的手机都好好的。kotlin我这边也没有调用，我发现Jpay里面的issue也有人提这个问题，但是也没解决

**Comment by oneLZH** [comment]
> > @oneLZH 该问题是否解决 我前面也遇到，提了issue，但是后面说新版已经没有使用WXPayActivit，所以暂时也没处理。
> 
> 你有稳定复现步骤么？麻烦提供下

这个是用户手机出现的，我这没有相关机型，没有稳定复现步骤~

**Comment by kingofglory** [comment]
> > @oneLZH 该问题是否解决 我前面也遇到，提了issue，但是后面说新版已经没有使用WXPayActivit，所以暂时也没处理。
> 
> 还没有解决，微信支付这块自己扩展用了

你自己改了之后，后面还有报吗？

**Comment by kingofglory** [comment]
> @kingofglory 我这边也是在友盟崩溃日志看到的 手头的手机都好好的。kotlin我这边也没有调用，我发现Jpay里面的issue也有人提这个问题，但是也没解决

Jpay的微信支付有明显借鉴我代码的痕迹，并且有些Bug EasyPay修复了它还没修复，哈哈

**Comment by pengjunhong** [comment]
@kingofglory 嗯  两份代码有共同之处 哈哈

**Comment by oneLZH** [comment]
> > > @oneLZH 该问题是否解决 我前面也遇到，提了issue，但是后面说新版已经没有使用WXPayActivit，所以暂时也没处理。
> > 
> > 
> > 还没有解决，微信支付这块自己扩展用了
> 
> 你自己改了之后，后面还有报吗？

没有再报这个错了

**Comment by pengjunhong** [comment]
@kingofglory 其实这个问题从字面看 是空指针异常，我在想有没有可能是在某些低内存手机上面 ，activity被回收掉导致的问题

**Comment by kingofglory** [comment]
> > > > @oneLZH 该问题是否解决 我前面也遇到，提了issue，但是后面说新版已经没有使用WXPayActivit，所以暂时也没处理。
> > > 
> > > 
> > > 还没有解决，微信支付这块自己扩展用了
> > 
> > 
> > 你自己改了之后，后面还有报吗？
> 
> 没有再报这个错了

你是怎么改的？

**Comment by oneLZH** [comment]
> > > > > @oneLZH 该问题是否解决 我前面也遇到，提了issue，但是后面说新版已经没有使用WXPayActivit，所以暂时也没处理。
> > > > 
> > > > 
> > > > 还没有解决，微信支付这块自己扩展用了
> > > 
> > > 
> > > 你自己改了之后，后面还有报吗？
> > 
> > 
> > 没有再报这个错了
> 
> 你是怎么改的？

**Comment by kongnanlive** [comment]
这个问题解决了?看样子应该是，WXPayActivity销毁重建后出现的crash

**Comment by kingofglory** [comment]
> 这个问题解决了?看样子应该是，WXPayActivity销毁重建后出现的crash
没有，这边无法复现。

**Comment by nianzixin** [comment]
WXPay.getInstance().getWXApi() 单例换成new object应该就好了

**Comment by oneLZH** [comment]
close qustion
