### ISSUE TITLE
IPayCallback匿名内部类导致Activity内存泄漏

### ISSUE THREAD

**Issue by VeerHan** [kingofglory/EasyPay#14]
IPayCallback匿名内部类持有外部Activity类的引用，当其传递给静态的sPayCallback后，导致外部Activity的内存无法释放

**Comment by kingofglory** [comment]
> IPayCallback匿名内部类持有外部Activity类的引用，当其传递给静态的sPayCallback后，导致外部Activity的内存无法释放

调用完支付以后都会给sPayCallback置空的。你确定是sPayCallback引用的么？把相关检测资料上传上来看看
