### ISSUE TITLE
这个库可以兼容微信官方推荐的写法吗

### ISSUE THREAD

**Issue by protectedMan** [kingofglory/EasyPay#18]
之前使用的是.wxapi.WXPayEntryActivity 方式实现的微信支付，请问如果集成了EasyPay方式的支付。 两种写法可以兼容并存吗？

**Comment by kingofglory** [comment]
估计不行，应该会被强制拦截到EasyPay指定的Activity吧，这个你可以试验一下。不过为什么要保留两种呢

**Comment by protectedMan** [comment]
> 估计不行，应该会被强制拦截到EasyPay指定的Activity吧，这个你可以试验一下。不过为什么要保留两种呢

保留两种是因为项目之前在WXPayEntryActivity写了太多逻辑，如果改动的话比较麻烦

**Comment by kingofglory** [comment]
你可以说说主要是哪些逻辑？这个Activity不是就接收个回调么？还是你这个activity也有界面？

**Comment by protectedMan** [comment]
我之前吊起微信支付都是这样写的，那我用了这个库，还能这样写吗，主要是因为老的代码我不想动了。
![image](https://user-images.githubusercontent.com/17565737/89856053-ca2c5080-dbca-11ea-8065-57bd3bf9a3aa.png)

**Comment by kingofglory** [comment]
能啊，我那边需要也是这些数据项而已，你传进去就行了。从api.registerApp这一行到最后api.sendReq替换成我这边封装的就可以了，很简单

**Comment by kingofglory** [comment]
你看这个方法里面的    WXPayInfoImpli 类，填的就是你上面那数据
private void wxpay(){
        //实例化微信支付策略
        WXPay wxPay = WXPay.getInstance();
        //构造微信订单实体。一般都是由服务端直接返回。
        WXPayInfoImpli wxPayInfoImpli = new WXPayInfoImpli();
        wxPayInfoImpli.setTimestamp("");
        wxPayInfoImpli.setSign("");
        wxPayInfoImpli.setPrepayId("");
        wxPayInfoImpli.setPartnerid("");
        wxPayInfoImpli.setAppid("");
        wxPayInfoImpli.setNonceStr("");
        wxPayInfoImpli.setPackageValue("");
        //策略场景类调起支付方法开始支付，以及接收回调。
        EasyPay.pay(wxPay, this, wxPayInfoImpli, new IPayCallback() {
            @Override
            public void success() {
                toast("支付成功");
            }

            @Override
            public void failed(int code, String msg) {
                toast("支付失败");
            }

            @Override
            public void cancel() {
                toast("支付取消");
            }
        });
    }

**Comment by protectedMan** [comment]
WXPayEntryActivity的逻辑也要挪一下吧

**Comment by kingofglory** [comment]
你还有啥逻辑，放到我这边回调里应该就可以了吧
