### ISSUE TITLE
支付宝版本过于低

### ISSUE THREAD

**Issue by penglin2015** [kingofglory/EasyPay#2]
很多平台提示了支付宝版本过低，提醒更新到最新版本

**Comment by mmc-mu** [comment]
同支付宝版本过低，只能下载源码自己集成了

**Comment by kingofglory** [comment]
> 同支付宝版本过低，只能下载源码自己集成了

EasyPay v2.0.0已正式发布。所有支付SDK已同步更新，并且再次精简微信支付集成代码，欢迎试用。
