### ISSUE TITLE
项目在Kotlin中调用有点问题

### ISSUE THREAD

**Issue by simplepeng** [kingofglory/EasyPay#4]
### 1
> implementation files('libs/alipaySdk-15.6.5-20190718211159-noUtdid.aar') 改为api方式引用
### 2
`WXPay.getInstance().onResp(baseResp.errCode, baseResp.errStr)`的`onResp`方法的参数
`IPayCallback`的`failed(int code, @Nullable String message)`方法的参数
加上`@Nullable`注解，不然会报如下错误
> E/MicroMsg.SDK.WXApiImplV10: handleIntent fail, ex = Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter msg

**Comment by kingofglory** [comment]
> ## 建议
> ### 1
> > implementation files('libs/alipaySdk-15.6.5-20190718211159-noUtdid.aar') 改为api方式引用
> 
> ### 2
> `WXPay.getInstance().onResp(baseResp.errCode, baseResp.errStr)`的`onResp`方法的参数
> `IPayCallback`的`failed(int code, @Nullable String message)`方法的参数
> 加上`@Nullable`注解，不然会报如下错误
> 
> > E/MicroMsg.SDK.WXApiImplV10: handleIntent fail, ex = Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter msg

好的，我看看。第一条，你是在外面还有引用支付宝SDK代码是吗？第二条，你是碰到空的情况了吗？怎么出现的？

**Comment by simplepeng** [comment]
嗯，是的，第一条是在直接gradle依赖Alipay的引用出现的，报找不到Alipay相关Class的错误，
第二条是用kotlin写回调的时候，如果message为空的时候就会报错。

**Comment by asjqkkkk** [comment]
> 嗯，是的，第一条是在直接gradle依赖Alipay的引用出现的，报找不到Alipay相关Class的错误，
> 第二条是用kotlin写回调的时候，如果message为空的时候就会报错。

第一个问题，目前依旧存在。
使用api的方式貌似也是不行的。
目前有解决方案吗😳

**Comment by kingofglory** [comment]
> 嗯，是的，第一条是在直接gradle依赖Alipay的引用出现的，报找不到Alipay相关Class的错误，
> 第二条是用kotlin写回调的时候，如果message为空的时候就会报错。

两个问题已经解决。哥们，有空验证一下。

**Comment by kingofglory** [comment]
2.0.1已推送。

**Comment by meiyoucai** [comment]
alipay支付还是会报找不到  Didn't find class "com.alipay.sdk.app.PayTask" 这个得怎么解决啊 都升级到2.0.1了

**Comment by kingofglory** [comment]
> alipay支付还是会报找不到 Didn't find class "com.alipay.sdk.app.PayTask" 这个得怎么解决啊 都升级到2.0.1了

你先用下载源码集成方式吧。这个问题我在处理中。

**Comment by Leovany** [comment]
> > alipay支付还是会报找不到 Didn't find class "com.alipay.sdk.app.PayTask" 这个得怎么解决啊 都升级到2.0.1了
> 
> 你先用下载源码集成方式吧。这个问题我在处理中。

我也遇到这个问题了，希望大大能尽快处理一下，大大辛苦了
PS：这个EasyPay真的很强大好用，希望能在集成下 QQ钱包
